function countingValleys(steps: number, path: string): number {
  let letters: string[] = path.split("");
  let valleys: number = 0;

  let hikeUp: string[] = [];
  let hikeDown: string[] = [];

  letters.forEach((letter, index) => {
    letter == "U" ? hikeUp.push(letter) : hikeDown.push(letter);
    if (hikeUp.length == hikeDown.length) {
      letter == "U" ? valleys++ : null;
    }
  });

  //? Return number of valleys traversed
  return valleys;
}

// const mountainsAndValleys: { steps: number; path: string; result: number }[] = [
//   {
//     steps: 8,
//     path: "UDDDUDUU",
//     result: 1,
//   },
//   {
//     steps: 12,
//     path: "DDUUDDUDUUUD",
//     result: 2,
//   },
//   {
//     steps: 10,
//     path: "UDUUUDUDDD",
//     result: 1,
//   },
//   {
//     steps: 10,
//     path: "UDDDUDUDUU",
//     result: 1,
//   },
//   {
//     steps: 100,
//     path: "DUDUUUUUUUUDUDDUUDUUDDDUUDDDDDUUDUUUUDDDUUUUUUUDDUDUDUUUDDDDUUDDDUDDDDUUDDUDDUUUDUUUDUUDUDUDDDDDDDDD",
//     result: 2,
//   },
//   {
//     steps: 100,
//     path: "DDUDUDDUDDUDDUUUUDUDDDUUDDUUDDDUUDDUUUUUUDUDDDDUDDUUDUUDUDUUUDUUUUUDDUDDDDUDDUDDDDUUUUDUUDUUDUUDUDDD",
//     result: 5,
//   },
//   {
//     steps: 100,
//     path: "UDUDDUUUDUDUDUUDUUDDDDDUDUDDDDUUDDUDDUUUUDUUDUDDDDUDUDUUUDDDUUUDUDDUUDDDUUDDUDDDUDUUDUUDUUDUDDDUUUUU",
//     result: 6,
//   },
//   {
//     steps: 1000,
//     path: "UDDDUUDUUDDDDUUDDUDDDUUDDDUUDDUUDUDUDDDDUUDDDDDDUUUDUDUDUUDUUUUUUUUUUUDUUUUUDUDUDUDDDDUUDUUUDDDDDUUDUUDUUUUUUDDDDDUUDUUDDDUDUUUUUUUDUUUUDDUDDDDDUUUDDUUUUUUUDDDDUUUDUUUDUUUUUUUDDUUUDDDDUUDUDDDUDDDDUUDDDDDUUDUDDUDUUUDDUDUDDDUUDDUDUUUUUDDUUUDUUUUUUDDUDUUDDUUDDDUDUDDDDUDUDDUUUDDDUDDUDDUUUUDDDUDUDDDUUUUUDUUUDDUDUUDUUUDDUDUUUDUDUDUUUUDDUDDDUUUDDDUDUDDDDDDDUUUUDDUUDUUUDUDUDUDDUUUDDUDUDDUDDUDDDUDUDUDDUUDDDUUDUUDUDDDDDDDDUUDDUUDDUUUUUUDUUUDDUUDUDDUUDDDUDDUUUUUDUDUDDDUUUDDUUDDDUDUUDUUDDDUDDUUDUUUDDUUUUDUUUDDDDUDUUUDDUDDDDDDDUDDDUUDUDDUDUDUUDUDDUUDUUDUUDUUDUDDDUUDDUUUUDUUDUUDUUUUDUUUDDUUUDDUDUDDUDUDUUUDUDDDUUUUDUUDUUUDDUUDUDUDDDDUDUDDDDDUUUDUUUDUDDUUUDUUUUDDUUUDDDUDUDUUDUUUUUDUUDDDUUDDUDDDDUUUDUUUUUDDUUUUUDDUUDUDDUDUDUUUUDUUDUUUDUUDDDUUUUDDDUDUDUUDUDUUDDDUDDUUDDUDUDUUDUDUDDDUDDDUDDDDUDUUUUUDUDUDUUDUUDUDDUDUUDDUUDUDUDDDDUDDUDDUDDUUUUDUDDUUUUDUUDUDDUDDDUDUUUDUDUDUDDDUDDUUUUDDUDUDUDDUDDDUDDDUUUDUDUDUUDUUUUUDUDDDDUUDDDDUDUDDUDDDDUUUDUDUUDUDUUUDDUDUDDDDDUUDUDUUDDDDUUDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
//     result: 3,
//   },
// ];

// mountainsAndValleys.forEach((item) => {
//   console.log(countingValleys(item.steps, item.path));
// });

export { countingValleys };
